spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /platzi-market/api
  port: 8080

---
# Dev environment configuration
spring:
  profiles: dev
server:
  port: 8090

---
# Pdn environment configuration
spring:
  profiles: pdn
server:
  port: 80